const fs = require('fs');
const path = require('path');

// Load package.json to get the app name for executableName
const packageJson = require('./package.json');
const executableName = packageJson.name;

// Load update config if it exists (generated by prepare-action.js when auto-update is enabled)
const updateConfigPath = path.join(__dirname, 'update-config.json');
let publishConfig = null;
if (fs.existsSync(updateConfigPath)) {
  try {
    publishConfig = JSON.parse(fs.readFileSync(updateConfigPath, 'utf8'));
  } catch (e) {
    console.warn('Failed to load update-config.json:', e.message);
  }
}

module.exports = {
  packagerConfig: {
    asar: true,
    icon: './assets/AppIcon',
    executableName: executableName,
    ignore: [
      'assets',
      'forge.config.js',
      'package-lock.json',
      'update-config.json',
    ]
  },
  rebuildConfig: {},
  makers: [
    {
      name: '@electron-forge/maker-squirrel',
      config: {},
    },
    {
      name: '@electron-forge/maker-zip',
      platforms: ['darwin'],
    },
    {
      name: '@electron-forge/maker-deb',
      config: {
        options: {
            icon: './assets/AppIcon.png'
          }
      },
    },
    {
      name: '@electron-forge/maker-rpm',
      config: {},
    },
    {
      name: '@electron-forge/maker-dmg',
      config: {
        background: './assets/dmg-background.png',
        format: 'ULFO',
      }
    },
  ],
  plugins: [
    {
      name: '@electron-forge/plugin-auto-unpack-natives',
      config: {},
    },
  ],
  ...(publishConfig && {
    publishers: [
      {
        name: '@electron-forge/publisher-github',
        config: {
          repository: {
            owner: publishConfig.owner,
            name: publishConfig.repo,
          },
          prerelease: false,
          draft: false,
        },
      },
    ],
  }),
};
